### ISSUE TITLE
Make RPG less shitty

### ISSUE THREAD

**Issue by LeonWilzer** [lukaslangrock/Informatik#7]
- [ ] **The planning**: insanely stupid and nonsensical.
- _Suggested Solution: Independent._

- [ ] **The code:** barely comprehensible, but functional.
-   _Suggested Solution: Implement all tools and classes a proper game needs._

- [ ] **The gameplay:** non-existent.
-   _Suggested Solution: Give the player (more) agency._

**Comment by lukaslangrock** [comment]
prehaps in the holidays?
